[package]
name = "natsume-device-protocol"
description = "Natsume QUIC control-session Protobuf schema and Rust facade"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
build = "build.rs"

[dependencies]
prost.workspace = true

[build-dependencies]
snafu.workspace = true
prost-build = "0.14"
protoc-bin-vendored = "3"

[lints]
workspace = true
