[package]
name = "natsume-server"
description = "Natsume V2 control server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
argon2.workspace = true
axum.workspace = true
clap.workspace = true
cookie.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true
getrandom.workspace = true
hex.workspace = true
natsume-error-code = { path = "../crates/error-code" }
percent-encoding.workspace = true
rpassword.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
snafu.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
rcgen.workspace = true
regex.workspace = true
rustls = { workspace = true, features = ["tls12"] }
tower.workspace = true

[lints]
workspace = true
